[workspace]
resolver = "2"
members = ["aoc-2015-01-1", "aoc-2015-01-2", "aoc-2015-02-1", "aoc-2015-02-2", "aoc-2015-03-1", "aoc-2015-03-2", "aoc-2015-04-1", "aoc-2015-04-2", "aoc-2015-05-1"]

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
